# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/src/components/postgres_example_gen/proto/postgres_connection_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='app/src/components/postgres_example_gen/proto/postgres_connection_config.proto',
  package='tfx.examples.custom_components.postgres_example_gen',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nNapp/src/components/postgres_example_gen/proto/postgres_connection_config.proto\x12\x33tfx.examples.custom_components.postgres_example_gen\"\xbe\x01\n\x18PostgresConnectionConfig\x12\x0e\n\x04host\x18\x01 \x01(\tH\x00\x12\x0e\n\x04port\x18\x02 \x01(\rH\x01\x12\x12\n\x08\x64\x61tabase\x18\x03 \x01(\tH\x02\x12\x12\n\x08username\x18\x04 \x01(\tH\x03\x12\x12\n\x08password\x18\x05 \x01(\tH\x04\x42\n\n\x08opt_hostB\n\n\x08opt_portB\x0e\n\x0copt_databaseB\x0e\n\x0copt_usernameB\x0e\n\x0copt_passwordb\x06proto3'
)




_POSTGRESCONNECTIONCONFIG = _descriptor.Descriptor(
  name='PostgresConnectionConfig',
  full_name='tfx.examples.custom_components.postgres_example_gen.PostgresConnectionConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='tfx.examples.custom_components.postgres_example_gen.PostgresConnectionConfig.host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='tfx.examples.custom_components.postgres_example_gen.PostgresConnectionConfig.port', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='database', full_name='tfx.examples.custom_components.postgres_example_gen.PostgresConnectionConfig.database', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='username', full_name='tfx.examples.custom_components.postgres_example_gen.PostgresConnectionConfig.username', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='tfx.examples.custom_components.postgres_example_gen.PostgresConnectionConfig.password', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='opt_host', full_name='tfx.examples.custom_components.postgres_example_gen.PostgresConnectionConfig.opt_host',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='opt_port', full_name='tfx.examples.custom_components.postgres_example_gen.PostgresConnectionConfig.opt_port',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='opt_database', full_name='tfx.examples.custom_components.postgres_example_gen.PostgresConnectionConfig.opt_database',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='opt_username', full_name='tfx.examples.custom_components.postgres_example_gen.PostgresConnectionConfig.opt_username',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='opt_password', full_name='tfx.examples.custom_components.postgres_example_gen.PostgresConnectionConfig.opt_password',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=136,
  serialized_end=326,
)

_POSTGRESCONNECTIONCONFIG.oneofs_by_name['opt_host'].fields.append(
  _POSTGRESCONNECTIONCONFIG.fields_by_name['host'])
_POSTGRESCONNECTIONCONFIG.fields_by_name['host'].containing_oneof = _POSTGRESCONNECTIONCONFIG.oneofs_by_name['opt_host']
_POSTGRESCONNECTIONCONFIG.oneofs_by_name['opt_port'].fields.append(
  _POSTGRESCONNECTIONCONFIG.fields_by_name['port'])
_POSTGRESCONNECTIONCONFIG.fields_by_name['port'].containing_oneof = _POSTGRESCONNECTIONCONFIG.oneofs_by_name['opt_port']
_POSTGRESCONNECTIONCONFIG.oneofs_by_name['opt_database'].fields.append(
  _POSTGRESCONNECTIONCONFIG.fields_by_name['database'])
_POSTGRESCONNECTIONCONFIG.fields_by_name['database'].containing_oneof = _POSTGRESCONNECTIONCONFIG.oneofs_by_name['opt_database']
_POSTGRESCONNECTIONCONFIG.oneofs_by_name['opt_username'].fields.append(
  _POSTGRESCONNECTIONCONFIG.fields_by_name['username'])
_POSTGRESCONNECTIONCONFIG.fields_by_name['username'].containing_oneof = _POSTGRESCONNECTIONCONFIG.oneofs_by_name['opt_username']
_POSTGRESCONNECTIONCONFIG.oneofs_by_name['opt_password'].fields.append(
  _POSTGRESCONNECTIONCONFIG.fields_by_name['password'])
_POSTGRESCONNECTIONCONFIG.fields_by_name['password'].containing_oneof = _POSTGRESCONNECTIONCONFIG.oneofs_by_name['opt_password']
DESCRIPTOR.message_types_by_name['PostgresConnectionConfig'] = _POSTGRESCONNECTIONCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PostgresConnectionConfig = _reflection.GeneratedProtocolMessageType('PostgresConnectionConfig', (_message.Message,), {
  'DESCRIPTOR' : _POSTGRESCONNECTIONCONFIG,
  '__module__' : 'app.src.components.postgres_example_gen.proto.postgres_connection_config_pb2'
  # @@protoc_insertion_point(class_scope:tfx.examples.custom_components.postgres_example_gen.PostgresConnectionConfig)
  })
_sym_db.RegisterMessage(PostgresConnectionConfig)


# @@protoc_insertion_point(module_scope)
